### ISSUE TITLE
[Bug]: split_rows_by when setting both (split_fun = drop_split_levels and page_by = TRUE) for empty table fails

### ISSUE THREAD

**Issue by clarkliming** [insightsengineering/rtables#651] opened 2023-06-08 06:59 UTC
### What happened?

split_rows_by with split_fun = drop_split_levels and page_by = TRUE for empty table fails with error

Error in TableTree(kids = inner, name = obj_name(spl), labelrow = LabelRow(label = obj_label(spl),  : 
  Got a page title prefix for an Elementary Table

### sessionInfo()

```R
R version 4.2.2 Patched (2022-11-10 r83330)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.5 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] scda_0.1.5.9005    tern_0.8.2.9006    rtables_0.6.1.9002 magrittr_2.0.3    
[5] formatters_0.5.0  

loaded via a namespace (and not attached):
 [1] pillar_1.8.1     compiler_4.2.2   forcats_1.0.0    tools_4.2.2     
 [5] digest_0.6.31    jsonlite_1.8.4   lifecycle_1.0.3  tibble_3.1.8    
 [9] gtable_0.3.1     checkmate_2.1.0  lattice_0.20-45  pkgconfig_2.0.3 
[13] rlang_1.0.6      Matrix_1.5-3     cli_3.6.0        fastmap_1.1.0   
[17] withr_2.5.0      dplyr_1.1.0      generics_0.1.3   vctrs_0.5.2     
[21] grid_4.2.2       tidyselect_1.2.0 glue_1.6.2       R6_2.5.1        
[25] fansi_1.0.4      Rdpack_2.4       survival_3.5-3   ggplot2_3.4.1   
[29] purrr_1.0.1      tidyr_1.3.0      backports_1.4.1  scales_1.2.1    
[33] htmltools_0.5.4  rbibutils_2.2.13 splines_4.2.2    colorspace_2.1-0
[37] utf8_1.2.3       munsell_0.5.0    broom_1.0.3     

```

reprex
```R
library(scda)
library(rtables)

adsl <- synthetic_cdisc_dataset("latest", "adsl")
adeg <- synthetic_cdisc_dataset("latest", "adeg")

adeg_f <- adeg %>%
  dplyr::filter(AVISIT != "SCREENING") %>%
  dplyr::filter(AGE > 1000)


# Define the split function
split_fun <- drop_split_levels

lyt <- basic_table(show_colcounts = TRUE) %>%
  split_cols_by("ARM") %>%
  split_rows_by("PARAMCD", split_fun = split_fun, page_by = TRUE, label_pos = "hidden", split_label = 'asda', labels_var = "PARAM") %>%
  split_rows_by("AVISIT", split_fun = split_fun, label_pos = "topleft", split_label = obj_label(adeg_f$AVISIT)) %>%
  analyze("AGE")
result <- build_table(lyt, adeg_f)
```

**Comment by shajoezhu** [comment] 2023-07-12 08:12
hi @gmbecker , I followed up with @clarkliming today. 

for outputting this kinda of degenerative table, there is a way chevron handling downsteam. But we just need the code not to stop here. If we could get some warning message printed, that would be nice. and it returns null table would be fine. Thanks!

**Comment by gmbecker** [comment] 2023-07-12 15:29
@shajoezhu, @clarkliming  again, not really. Printing anything at all is wrong here. There are 0 pages to print. And unlike other situations, table structure sanitization won't work here.

The issue is that you have asked rtables to create a table that paginates for each level of a variable, and that variable has zero levels, so there are no pages. This is different from other degenerate tables. This is an invalid table. The only thing that `export_as_txt` could possibly emit here is the empty string. no titles, no column headers, nothing at all. I don't see any value in that.

**Comment by clarkliming** [comment] 2023-07-12 15:50
I don't think the exported content matters in this case. I just need the workflow, constructing layout construction and building table, to work without errors. returning something like null table should be sufficient. chevron will take over the rest and won't export that generated empty table.

**Comment by clarkliming** [comment] 2023-07-12 16:22
> returning a null table (which I assume means a table with no rows and no columns?) doesn't make sense here because it doesn't match the layout being applied to the data.

then give something that is not an error

**Comment by shajoezhu** [comment] 2023-07-12 17:32
> @shajoezhu, @clarkliming again, not really. Printing anything at all is wrong here. There are 0 pages to print. And unlike other situations, table structure sanitization won't work here, because the issue isn't that there are no rows, the issues is that there are no facets, which correspond to pages of output

> The issue is that you have asked rtables to create a table that paginates for each level of a variable, and that variable has zero levels, so there are no pages. This is different from other degenerate tables. This is an invalid table. The only thing that export_as_txt could possibly emit here is the empty string. no titles, no column headers, nothing at all. I don't see any value in that.

Hi @gmbecker , thanks for the comments. we have not called `export_as_txt` yet. The example currently fails at the step `build_table(lyt, adeg_f)`, which one would expect the function to return an rtable object at this stage. 

error says
`Error in TableTree(kids = inner, name = obj_name(spl), labelrow = LabelRow(label = obj_label(spl), :
Got a page title prefix for an Elementary Table`

for this case, can we add a check at the begining of build_table, check the value for page_by, if the data is empty, skip page_by?

**Comment by gmbecker** [comment] 2023-07-12 20:25
> > @shajoezhu, @clarkliming again, not really. Printing anything at all is wrong here. There are 0 pages to print. And unlike other situations, table structure sanitization won't work here, because the issue isn't that there are no rows, the issues is that there are no facets, which correspond to pages of output
> 
> > The issue is that you have asked rtables to create a table that paginates for each level of a variable, and that variable has zero levels, so there are no pages. This is different from other degenerate tables. This is an invalid table. The only thing that export_as_txt could possibly emit here is the empty string. no titles, no column headers, nothing at all. I don't see any value in that.
> 
> Hi @gmbecker , thanks for the comments. we have not called `export_as_txt` yet. The example currently fails at the step `build_table(lyt, adeg_f)`, which one would expect the function to return an rtable object at this stage.
> 
> error says `Error in TableTree(kids = inner, name = obj_name(spl), labelrow = LabelRow(label = obj_label(spl), : Got a page title prefix for an Elementary Table`
> 
> for this case, can we add a check at the begining of build_table, check the value for page_by, if the data is empty, skip page_by?

I don't think so. I'm very much not a fan of functions that don't do what they're told. Its confusing to users, makes systems difficult (at best) to reason about, and is, imho, just extremely bad practice. 

An example of this is the fact that at on point tibble/dplyr ignored `drop = TRUE`, as if the user had not intentionally typed that out (because its no longer the default when working in that framework).  Even the tidyverse devs have pulled back from that, as it is no longer the case.

All of that is to say that if the caller gives a layout that that says a split should be a page by split, then it is not `rtables`' place to say "yeah, I know you said you want this split to be page by, but I know better than you and I've decided it isn't gonna be, kthxbye".

The onus here really is correctly on the caller (chevron) not the foundational building block (rtables).

That said, much like other degenerate table-related issues, there is a way forward. Namely what @BFalquet says here https://github.com/insightsengineering/rtables/issues/679#issuecomment-1627819638 and my following response.

In short, in addition to validating table structure there are some things we can do to validate _layouts_ with respect to incoming data. We do this currently within `build_table`, but it can be pulled out into a standalone utility that can be called on layouts before tabulation is attempted, if we want. 

Honestly, though. I think the easiest way forward here is to have chevron check early in the process whether the data is empty after processing, and just do whatever they want to in the "there's no data the table doesn't make sense" case, which could be any of the following depending on the situation:

- build a table with a bunch of 0s in it (split on factors with no drop_split_levels)
- build a degenerate non-page_by table and then sanitize,
- short circuit and emit "the null table" (whatever that means), or
- write an error to the log and not emit a table at all.


I know this message is already long and covers a number of points, but for the record, another one: the reason we can't sanitize pageby-degenerate tables the way we can normally degenerate ones is that missing rows isn't the issue, its _missing facets_. So we would have to add a facet (which in this case is a page) and THEN sanitize so that page has a row on it. See my next comment

**Comment by gmbecker** [comment] 2023-07-12 21:14
Work-around for this issue: Our problem is that there are no facets, but page-by splitting requires there to be at least one or else the table as a whole is invalid (beyond just being degenerate).

So lets add one.

```
add_safety_facet <- function(ret, spl, .spl_context, fulldf) {
    if(length(ret$datasplit) == 0)
        ret <- add_to_split_result(ret, values = list("XXX NO LEVELS OBSERVED XXX"),
                                   labels = "XXX NO LEVELS OBSERVED XXX",
                                   datasplit = list(fulldf[0,]))
    ret
}


safe_drop_split_levels <- make_split_fun(pre = list(drop_facet_levels),
                             post = list(add_safety_facet))

adsl <- synthetic_cdisc_dataset("latest", "adsl")
adeg <- synthetic_cdisc_dataset("latest", "adeg")

adeg_f <- adeg %>%
  dplyr::filter(AVISIT != "SCREENING") %>%
  dplyr::filter(AGE > 1000)


# Define the split function
split_fun <- drop_split_levels_safe

lyt <- basic_table(show_colcounts = TRUE) %>%
  split_cols_by("ARM") %>%
  split_rows_by("PARAMCD", split_fun = safe_drop_split_levels, page_by = TRUE, label_pos = "hidden", split_label = 'asda', labels_var = "PARAM") %>%
  split_rows_by("AVISIT", split_fun = drop_split_levels, label_pos = "topleft", split_label = obj_label(adeg_f$AVISIT)) %>%
  analyze("AGE")
result <- build_table(lyt, adeg_f)

```
This will currently give a warning but I will be removing that as this is a valid usage.

Note this doesn't give us a non-degenerate table (there's still no rows) but if we sanitize, everything is good. Thus assuming @edelarua's fix for #653 is in place in our copy of formatters, we get:

```
> paginate_table(sanitize_table_struct(result))
$`XXX NO LEVELS OBSERVED XXX`

asda: XXX NO LEVELS OBSERVED XXX

——————————————————————————————————————————————————————————
Analysis Visit   A: Drug X    B: Placebo    C: Combination
                   (N=0)         (N=0)          (N=0)     
——————————————————————————————————————————————————————————
                    -- This Section Contains No Data --   
```

**Comment by Melkiades** [comment] 2023-07-13 17:33
> In short, in addition to validating table structure there are some things we can do to validate _layouts_ with respect to incoming data. We do this currently within `build_table`, but it can be pulled out into a standalone utility that can be called on layouts before tabulation is attempted, if we want.
> 
> Honestly, though. I think the easiest way forward here is to have chevron check early in the process whether the data is empty after processing, and just do whatever they want to in the "there's no data the table doesn't make sense" case, which could be any of the following depending on the situation:
> 
> * build a table with a bunch of 0s in it (split on factors with no drop_split_levels)
> * build a degenerate non-page_by table and then sanitize,
> * short circuit and emit "the null table" (whatever that means), or
> * write an error to the log and not emit a table at all.

Is not this table exactly something that build_table should detect? I think that splitting on an empty column should be caught when the data is inserted and if no row is present at all it could make sense just to throw an early error saying that the table is virtually missing

About validating the layout, I think it is a greatidea and in the `.spl_context` PR I tried to do that but it is still not easy to follow the complex structure for validation in a meaningful way (for me ^^)

**Comment by gmbecker** [comment] 2023-07-13 21:54
@Melkiades a few things.

> Is not this table exactly something that build_table should detect? I think that splitting on an empty column should be caught when the data is inserted and if no row is present at all it could make sense just to throw an early error saying that the table is virtually missing

Yes, I'm arguing for this to be an error that is thrown early (and is intelligible, there actually already is an error thrown at build_table time, but its not going to be understandable by users).

@clarkliming's position, AFAIK, is that `build_table` should complete, and return something, and my post above was pushing back on that and explaining my reasoning for doing so.

>  About validating the layout, I think it is a great idea and in the .spl_context PR I tried to do that but it is still not easy to follow the complex structure for validation in a meaningful way (for me ^^)

 Validating a layout will be an operation that happens much earlier than anything to do with the split context work. This complicates the optional column info in split context angle, but is unavoidable because, as the name suggests, validating a layout is an operation on the full layout, which is not present when the splitcontext is being constructed.

**Comment by gmbecker** [comment] 2023-08-11 23:10
Closing this as completed via the structure sanitization functionality

**Comment by shajoezhu** [comment] 2023-08-12 09:45
Hi @gmbecker , can you please reference the PR in this issue please. Thanks

**Comment by Melkiades** [comment] 2023-08-14 15:04
> Closing this as completed via the structure sanitization functionality

I do not think this is completed as it is missing the complete implementation of the checks in build_table and the downstream corrections. Keeping track of this in #679

**Closed** 2023-08-22 23:07 UTC
Labels: bug, priority, sme
